#!/usr/bin/env bash
set -euo pipefail

MODULE_PATH=$1
PR_NUMBER=$2
ROOT_DIR=$(pwd)

TOTAL=$(cat "$ROOT_DIR/.total_cost")
ANALYSIS=$(cat "$ROOT_DIR/.gemini_output")

echo "📝 Posting comment to PR #$PR_NUMBER..."

cat > comment.md <<EOF
## 💰 FinOps Gate: \`$MODULE_PATH\`

| Metric | Value |
|:-------|:------|
| **Direct Monthly Cost** | **\$$TOTAL** |
| **Status** | $( (( $(echo "$TOTAL > 0" | bc -l) )) && echo "💸 Billable" || echo "👻 Potential Shadow Costs" ) |

---

### 🧠 Gemini Architect Analysis
$ANALYSIS

---
*Generated by Terraform FinOps Pipeline*
EOF

gh pr comment "$PR_NUMBER" --body-file comment.md
