#!/usr/bin/env bash
set -euo pipefail

# The module directory passed as the first argument
MODULE="$1"
ROOT_DIR=$(pwd)

echo "🚀 Starting FinOps Audit for module: $MODULE"

# 1. Navigate to module and cleanup
cd "$MODULE"
rm -f plan.tfplan plan.json infracost.json gemini.md prompt.txt gemini_request.json

# 2. Run Terraform Plan
echo "📦 Running Terraform Plan..."
terraform init -input=false
terraform plan -out=plan.tfplan -input=false
terraform show -json plan.tfplan > plan.json

# 3. Run Infracost
echo "💰 Running Infracost Breakdown..."
infracost breakdown \
  --path plan.json \
  --format json \
  --out-file infracost.json

# Extract total monthly cost
TOTAL=$(jq '[.projects[].breakdown.totalMonthlyCost | tonumber] | add // 0' infracost.json)
echo "✅ Total monthly cost: \$$TOTAL"

# 4. Build Gemini prompt safely
# This uses the 'infrav7' requirements for a detailed shadow-cost analysis
cat > prompt.txt <<EOF
You are a Senior GCP FinOps Architect.

Module: $MODULE
Direct Monthly Cost: $TOTAL USD

Analyze ALL Terraform resources provided in the data.

If direct cost is 0, do NOT simply say zero. 
Explain usage-based shadow costs such as:
- network egress
- NAT processing
- logging ingestion
- load balancer data processing
- scaling exposure

Provide:
1) Cost classification (Fixed or Usage-Based)
2) Shadow cost explanation
3) Risk rating
4) Optimization recommendation

Return markdown tables only.

RAW INFRACOST DATA:
$(cat infracost.json)
EOF

# 5. Convert safely to JSON using jq --rawfile
# This prevents "Unexpected token" errors from special characters
jq -n --rawfile text prompt.txt \
  '{contents:[{parts:[{text:$text}]}]}' \
  > gemini_request.json

# 6. Call Gemini API
echo "🤖 Requesting Gemini AI Review..."
RESPONSE=$(curl -sS -X POST \
  "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent" \
  -H "Content-Type: application/json" \
  -H "x-goog-api-key: ${GEMINI_API_KEY}" \
  --data-binary @gemini_request.json || echo "CURL_ERROR")

# 7. Parse Response
if [[ "$RESPONSE" == "CURL_ERROR" ]]; then
  echo "⚠️ Gemini API Error: Connection Failed" > gemini.md
elif echo "$RESPONSE" | jq -e '.candidates' >/dev/null 2>&1; then
  echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text' > gemini.md
else
  API_ERR=$(echo "$RESPONSE" | jq -r '.error.message // "Unknown API Error"')
  echo "⚠️ Gemini API Error: $API_ERR" > gemini.md
fi

# 8. Post PR Comment
# We go back to the root to ensure the 'gh' command and pathing are stable
cd "$ROOT_DIR"

{
  echo "## 💰 FinOps Audit: \`$MODULE\`"
  echo ""
  echo "| Metric | Value |"
  echo "|:-------|:------|"
  echo "| **Direct Monthly Cost** | **\$$TOTAL USD** |"
  echo ""
  echo "---"
  echo "## 🤖 Gemini Architect Review"
  echo ""
  cat "$MODULE/gemini.md"
  echo ""
  echo "---"
  echo "*Generated by Gemini 2.0 Flash + Infracost*"
} > comment.md

# Use the PR_NUMBER environment variable from the workflow
gh pr comment "$PR_NUMBER" --body-file comment.md

echo "✅ FinOps review completed for $MODULE."
